version: '3'

services:
  testing-project:
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/index.js
    ports:
      - "8000:8001"